### ISSUE TITLE
How to use?

### ISSUE THREAD

**Issue by nougator** [jython234/PyRakLib#1]
Hello I'm trying to do a server software in python and I want to use this lib but there is no documentation

**Comment by jython234** [comment]
This is a direct port of the original PHP RakLib (
https://github.com/PocketMine/RakLib). It would be used in the exact same
way as from php.

**Comment by nougator** [comment]
Thank you

**Comment by Heath123** [comment]
I can't find any docs for that either

**Comment by jython234** [comment]
I don't think any exist , you're right. You can see how it's used in the
PocketMine project, which it was created for.
