### ISSUE TITLE
Error

### ISSUE THREAD

**Issue by MFDGaming** [jython234/PyRakLib#3]
```Exception in thread Thread-2:
Traceback (most recent call last):
  File "/usr/lib/python3.8/threading.py", line 932, in _bootstrap_inner
    self.run()
  File "/root/Podrum-master/src/pyraklib/server/PyRakLibServer.py", line 90, in run
    SessionManager(self, socket)
  File "/root/Podrum-master/src/pyraklib/server/SessionManager.py", line 76, in __init__
    self.run()
  File "/root/Podrum-master/src/pyraklib/server/SessionManager.py", line 79, in run
    self.tickProcessor()
  File "/root/Podrum-master/src/pyraklib/server/SessionManager.py", line 88, in tickProcessor
    while --max and self.receivePacket(): pass
  File "/root/Podrum-master/src/pyraklib/server/SessionManager.py", line 154, in receivePacket
    self.getSession(source[0], source[1]).handlePacket(packet)
  File "/root/Podrum-master/src/pyraklib/server/Session.py", line 397, in handlePacket
    self.receivedWindow[packet.seqNumber] = packet.seqNumber
IndexError: deque index out of range

**Comment by MFDGaming** [comment]
@jython234

**Comment by alejzeis** [comment]
How are you using the library?

**Comment by MFDGaming** [comment]
by adding it in my project’s root (i used the github release)

**Comment by MFDGaming** [comment]
by the way i am making a implementation of pocketmine’s latest raklib http://github.com/mfdgaming/raknetpy

**Comment by MFDGaming** [comment]
ive also seen that you are trying to front decrement a value by the `--myvalue` method that does not exist in python. When doing `--myvalue` it is like doing `-1 * -myvalue` in python

**Comment by alejzeis** [comment]
I see. I wrote this quite a while ago as a port, so I don't quite remember
much about it.

**Comment by MFDGaming** [comment]
Yeah

**Comment by MFDGaming** [comment]
@jython234 out of curiosity, have you ever used pyraklib in a server software?

**Comment by alejzeis** [comment]
A long time ago I did for a little bit on an experiment with Minecraft: Pi
edition, but it never got anywhere really.

**Comment by MFDGaming** [comment]
Oh i asked because i tried to use it (i fixed all the issues it had at least all of them i found) and created a network interface and "bounded" it to pyraklib but i felt a bit as if it was handling nothing (when i had done everything right i belive)

**Comment by alejzeis** [comment]
I see. I tried to find my usage code for this but it appears I deleted it. All I remember was that it was meant to be used exactly the same way as the PHP version was written. It's possible that changes in Python versions might've caused weird stuff to happen, though it's unlikely. All I have apparently is [the test file](https://github.com/jython234/PyRakLib/blob/master/TestServer.py)

**Comment by alejzeis** [comment]
I've left the minecraft server development community a while ago, I should probably delete this and a lot of the other dead repositories I have since it appears they don't even work, I don't want to keep misleading people.

**Comment by MFDGaming** [comment]
@jython234 oh ok

**Comment by MFDGaming** [comment]
@jython234 thats my version that isnt crashing https://github.com/MFDGaming/PyRakLib-1.0.0

**Comment by MFDGaming** [comment]
oh also i found more bugs

**Comment by MFDGaming** [comment]
@jython234 could you make me a collaborator, I am thinking of fixing pyraklib?

**Comment by MFDGaming** [comment]
In fact I’ve already started

**Comment by alejzeis** [comment]
You can fork it if you want and continue on with it. I'm going to make this repo read-only since I'm not involved with this project and MCPE in general anymore.
