### ISSUE TITLE
Please update raklib

### ISSUE THREAD

**Issue by hayaz** [jython234/PyRakLib#4]
can you update raklib so that I can continue coding with my team mcpe bedrock server would be very nice of you

**Comment by MFDGaming** [comment]
@hayaz this library is broken

**Comment by alejzeis** [comment]
I'm marking this repo as read-only since it's no longer maintained by me, I've moved on to other projects. I do know @MFDGaming has forked it and worked on getting it functional for the more recent versions of minecraft.
